# web app action
name: 'Azure WebApp'
description: 'Deploy Web Apps/Containerized Web Apps to Azure. github.com/Azure/Actions'
inputs:
  publish-profile:
    description: 'Applies to Web Apps(Windows and Linux) and Web App Containers(linux). Multi container scenario not supported. Publish profile (*.publishsettings) file contents with Web Deploy secrets'
    required: false
  package:
    description: 'Applies to Web App only: Path to package or folder. *.zip, or a folder to deploy'
    required: false
    default: '.'

runs:
  using: 'node20'
  main: 'lib/main.js'
