git add --all;
$commitMsg = $args[0];
git commit -m $commitMsg;
git push; 
gh release delete v2 -y --cleanup-tag;  
gh release create v2 -n "";
gh workflow run -R 'joharasmus/moreFairStats' 'morefairstats.yml';
Start-Sleep -Seconds 5;
$runId = gh run list -R 'joharasmus/moreFairStats' --workflow=morefairstats.yml --json databaseId -q '.[0].databaseId';
gh run view -R 'joharasmus/moreFairStats' $runId --log;