on: workflow_dispatch

jobs:
  build_test_job:
    name: 'Build and test job'
    runs-on: ubuntu-24.04
    steps:

    - name: 'Checking out repo code'
      uses: actions/checkout@v4

    - name: 'Validate build'
      run: |
        npm install
